## provide the name of the namespace
namespace:
  name: dev

## define the image to execute with the Deployment 
image:
  repository:
     nginx
  tag:
     alpine

pullPolicy: IfNotPresent

resources:
  CPU:
    50m
  memory:
    256Mi

service:
  type:
    ClusterIP
  port: 8111

configMap:
  data: "version: alpine"

## set the number of replicas for an application 
replicaCount: 3